### ISSUE TITLE
Dependencies empty in package.json - missing a step?

### ISSUE THREAD

**Issue by amizzo87** [derbyparty/generator-derby#20]
Followed install instructions verbatim, got this:

```
> node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'derby'
```

It looks like the package.json's dependencies are completely empty. Shouldn't there be....well, many listed dependencies? Or did I miss a step? 

Thanks :)

**Comment by starikan** [comment]
Same error. After manual 'npm install' all works.

**Comment by zag2art** [comment]
fixed
