### ISSUE TITLE
derby.util.isProduction is undefined on client side

### ISSUE THREAD

**Issue by bsnote** [derbyparty/generator-derby#23]
When I create derby project using generator-derby and run it like this:
```
NODE_ENV=production node server
```
app is still available on client side, i.e. derby.util.isProduction is undefined here:
```
if (!derby.util.isProduction) global.app = app;
```

**Comment by zag2art** [comment]
For now I don't you `util.isProduction` on the client for globalling app. Instead I use [derby-debug](https://github.com/derbyjs/derby-debug) package. It export `app` as `APP` variable and `model` as `MODEL` in the browser console.
