### ISSUE TITLE
Is there a way to skip bundling for a faster restart?

### ISSUE THREAD

**Issue by rasteiner** [derbyparty/generator-derby#32]
It would be really nice if the browserify / bundling step could be skipped, for example when the server crashes and forever or pm2 or whatever restarts the app. The bundling can take quite a lot of time, especially when in NODE_ENV=production mode.

I'm talking about simply reusing the latest bundled .js file.

**Comment by zag2art** [comment]
You need to update your server.js file (if you use generator-derby) to something like this:
```js
var async = require('async');
var derby = require('derby');

var http  = require('http');
var chalk = require('chalk');

var publicDir = process.cwd() + '/public';

derby.run(function(){
  require('coffee-script/register');

  require('./server/config');

  var apps = [
    require('./apps/app')
    // <end of app list> - don't remove this comment
  ];

  var express = require('./server/express');
  var store = require('./server/store')(derby, publicDir);

  var error = require('./server/error');

  express(store, apps, error, publicDir, function(expressApp, upgrade){
    var server = http.createServer(expressApp);

    server.on('upgrade', upgrade);

    function listenServer(){
      server.listen(process.env.PORT, function() {
        console.log('%d listening. Go to: http://localhost:%d/',
            process.pid, process.env.PORT);
      });
    }

    function bundleApp (app, cb) {
      app.writeScripts(store, publicDir, {extensions: ['.coffee']}, function(err){
        if (process.env.MODE === 'save') app.serialize();

        if (err) {
          console.log("Bundle don't created:", chalk.red(app.name), ', error:', err);
        } else {
          console.log('Bundle created:', chalk.blue(app.name));
        }
        cb();
      });
    }

    switch (process.env.MODE) {
      case ('use'): return listenServer();
      case ('save'): return async.each(apps, bundleApp, process.exit.bind(process));
      default: async.each(apps, bundleApp, listenServer);
    } 
  });
});
```
After that you will be able to start your project three ways:

1. node server.js (usual way)
2. MODE=save node server.js (to save bundles and so on) 
3. MODE=use node server.js (to start you project using just created bundles)

**Comment by zag2art** [comment]
We use MODE=save in the deployment stage (while creating docker image) and MODE=use inside our docker container. Our 16 havy apps start on 8 second.

**Comment by rasteiner** [comment]
Thanks :+1:

**Comment by rasteiner** [comment]
For anyone that wants to try this out:
Once you have done a "MODE=save node server", derby creates a "derby-serialized" folder in each app folder. You need to delete those if you want to return to developing.

**Comment by zag2art** [comment]
Yeah, for the purpose we use npm-script in our `package.json`:
```
"clean": "find . -name 'derby-serialized' -type d | xargs /bin/rm -rf"
```
