### ISSUE TITLE
Error with derby-login

### ISSUE THREAD

**Issue by curran** [derbyparty/generator-derby#43]
Hello,

After a fresh project generation using `yo derby` with the following options:
- Redis
- Derby-login
  - Google
- Jade
- Stylus
- derby-router

After I run `npm-start`, I'm seeing the following error:

```
/Users/curran/repos/derbyTest2/node_modules/derby-login/lib/middleware/index.js:40
  backend.addProjection(options.publicCollection, options.collection, 'json0', options.user);
         ^

TypeError: Cannot read property 'addProjection' of undefined
  at Login.middleware (/Users/curran/repos/derbyTest2/node_modules/derby-login/lib/middleware/index.js:40:10)
  at module.exports (/Users/curran/repos/derbyTest2/server/express.js:36:21)
  at /Users/curran/repos/derbyTest2/server.js:24:3
  at Racer.Derby.run (/Users/curran/repos/derbyTest2/node_modules/derby/lib/Derby.server.js:17:5)
  at Object.<anonymous> (/Users/curran/repos/derbyTest2/server.js:9:7)
  at Module._compile (module.js:397:26)
  at Object.Module._extensions..js (module.js:404:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:429:10)
  at startup (node.js:139:18)
  at node.js:999:3
```

I did a little debugging, and it turns out that `backend` is undefined. This seems like an API change somewhere. Here are the versions of various packages from my generated `package.json`:

```
{
  "name": "derbytest2",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "async": "^1.5.2",
    "body-parser": "^1.14.2",
    "chalk": "^1.1.1",
    "coffee-script": "^1.10.0",
    "coffeeify": "^2.0.1",
    "compression": "^1.6.0",
    "connect-mongo": "^0.8.2",
    "cookie-parser": "^1.4.1",
    "derby": "^0.8.0",
    "derby-debug": "^0.1.0",
    "derby-jade": "^0.6.21",
    "derby-login": "^0.4.16",
    "derby-router": "^0.3.3",
    "derby-stylus": "^0.1.0",
    "express": "^4.13.3",
    "express-session": "^1.13.0",
    "passport-google-oauth": "^0.2.0",
    "racer-bundle": "^0.2.4",
    "racer-highway": "^7.0.0",
    "redis-url": "^1.2.1",
    "serve-favicon": "^2.3.0",
    "serve-static": "^1.10.0",
    "sharedb-mongo": "^0.8.7",
    "sharedb-redis-pubsub": "^0.3.1"
  },
  "author": {
    "name": "Curran",
    "email": "curran.kelleher@gmail.com"
  },
  "license": "",
  "readme": "derbytest2\n",
  "readmeFilename": "README.md"
}
```

Any ideas on this? I may try reverting some packages, like sharedb-mongo, to older releases and see if that makes the issue go away. Thank you.

In case it is relevant, here are my mongod and redis-server versions:

```
MacBook-2:derbyTest2 curran$ mongod --version
db version v2.6.7
MacBook-2:derbyTest2 curran$ redis-server --version
Redis server v=2.6.9 sha=00000000:0 malloc=libc bits=64
```

**Comment by curran** [comment]
I wonder if this may have something to do with these recent changes by @nateps https://github.com/derbyjs/racer/commit/726b29a7fea2a405eaa51d17b6ffdf5be59b2e79

Specifically, the line of code that assigns `backend` was removed: https://github.com/derbyjs/racer/commit/726b29a7fea2a405eaa51d17b6ffdf5be59b2e79#diff-5044e0717ba5ab44fb1f60c0668e2d3dL14

It looks like this change breaks derby-login.

**Comment by curran** [comment]
Possibly related to these recent commits in derby-login by @zag2art , which seem like they should fix the issue I'm encountering:
- take into account new ShareDb API https://github.com/derbyparty/derby-login/commit/4b2b677ca94cf64302dcb0480b3d611d312c5b8c
- fix ShareDB API changes https://github.com/derbyparty/derby-login/commit/96d5ba61fb8c635c9c6383282cd896ff44b0f78d

These assume a "store" object, but [in the generator template, the "store" is actually the "backend"](https://github.com/derbyparty/generator-derby/blob/master/app/templates/server/_store.js#L21):

```
  var store = derby.createBackend({
    db: db,
    pubsub: pubsub
  });
```

When I `console.log(store)`, I can see it is an instance of `Backend`:

```
Backend {
  domain: null,
  _events: { bundle: [ [Function], [Function] ] },
  _eventsCount: 1,
  _maxListeners: undefined,
  db: 
   DB {
     pollDelay: 0,
     disableIndexCreation: false,
     opIndexes: {},
     allowJSQueries: false,
     allowAggregateQueries: false,
     closed: false,
     mongo: null,
     mongoPoll: null,
     pendingConnect: [] },
  pubsub: 
   PubSub {
     prefix: undefined,
     nextStreamId: 1,
     streamsCount: 0,
     streams: {},
     subscribed: {},
     client: 
      RedisClient { ... },
     observer: 
      RedisClient { ... },
  extraDbs: {},
  projections: {},
  suppressPublish: false,
  maxSubmitRetries: null,
  middleware: {},
  agentsCount: 0,
  remoteAgentsCount: 0,
  racer: Racer { _plugins: [ [Function] ] },
  modelOptions: undefined }
```

**Comment by minicuper** [comment]
Yeah, @nateps changed api one more time. Thanks, @cjblomqvist here is PR for the changes. #https://github.com/derbyparty/derby-login/pull/37

**Comment by curran** [comment]
Ah I see. Thank you for looking into this so quickly.

**Comment by curran** [comment]
Auth is working correctly now with a newly generated project.
